AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Layout/LineLength:
  Max: 100
  AllowURI: true
  IgnoreCopDirectives: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/SymbolArray:
  Enabled: true

Style/WordArray:
  Enabled: true
  MinSize: 3

Naming/FileName:
  Exclude:
    - 'bin/*'
